version: '3'
services:
  back_app:
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    environment:
      - DB_URL=DB_URI
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: mongo
    container_name: db_mongo
    env_file:
      - .env
    volumes:
      - mongodata:/data/db
    ports:
      - ${DB_PORT}:${DB_PORT}

volumes:
  mongodata:
